Fea/change hamburger icon navbar
neerajdembla212/neerajdembla212.github.io pull request #10
Opened 2021-07-01 04:44 UTC by digvijay-gurav

2021-07-01 04:45 UTC, digvijay-gurav commented
Remove hamburger

2021-07-01 04:55 UTC, neerajdembla212 requested changes

2021-07-01 04:55 UTC, neerajdembla212 commented on LESS/navigation.less
> +.navBarMenuToggle {
please change the class names to kebab case as standardly used in theme. eg `navbar-menu-toggle`

2021-07-01 04:55 UTC, neerajdembla212 commented on LESS/navigation.less
> +  position: absolute;
Why do we need to add `position: absolute` ? current hamburger works fine without this property .

2021-07-03 13:47 UTC, neerajdembla212 commented
Closing this PR duplicate PR for https://github.com/neerajdembla212/neerajdembla212.github.io/pull/11

2021-07-03 13:47 UTC, closed without merging