strategy providers list view table row changes
neerajdembla212/neerajdembla212.github.io pull request #22
Opened 2021-07-07 04:53 UTC by digvijay-gurav

2021-07-07 05:57 UTC, neerajdembla212 requested changes

2021-07-07 05:57 UTC, neerajdembla212 commented on LESS/navigation.less
> +.ibox-content .table .return-percentage {
these css should be either in `custom.less` or create another file for strategic-provider page and import in style.less

2021-07-07 05:57 UTC, neerajdembla212 commented on css/style.css
> +  border: 1px solid #E7EDF4;
is this color picked from sigma ? if yes, create a variable @table-border-color in `variables.less` and use it here.

2021-07-07 17:35 UTC, digvijay-gurav reviewed
Made the suggested changes

2021-07-07 17:47 UTC, digvijay-gurav commented on LESS/navigation.less
> +.ibox-content .table .return-percentage {
Made the suggested changes

2021-07-07 17:47 UTC, digvijay-gurav commented on css/style.css
> +  border: 1px solid #E7EDF4;
Made the suggested changes

2021-07-08 04:04 UTC, neerajdembla212 approved these changes

2021-07-08 04:04 UTC, merged